feat: add secret module
TradrAPI/terraform-modules pull request #50
Opened 2024-05-23 13:51 UTC by elsebasan

add module to create aws secrets

2024-05-23 14:40 UTC, o-leolleo requested changes

2024-05-23 14:40 UTC, o-leolleo commented on aws/secrets/output.tf
> +}
```suggestion
    value = aws_secretsmanager_secret_version.secret.secret_string
    sensitive = true
}
```

2024-05-24 08:37 UTC, akhil-redacre approved these changes

2024-05-24 08:47 UTC, o-leolleo approved these changes

2024-05-24 08:47 UTC, merged